"use client";
import { useEffect,useMemo,useState } from "react";
import Link from "next/link";
import { Sidebar } from "@/components/sidebar";
type Product={id:string;name:string;sku:string;stock_quantity:number;minimum_stock:number;unit?:string;location?:string};
export default function Inventario(){
 const [products,setProducts]=useState<Product[]>([]),[q,setQ]=useState(""),[selected,setSelected]=useState<Product|null>(null),[qty,setQty]=useState(""),[type,setType]=useState("adjustment_in"),[reason,setReason]=useState(""),[msg,setMsg]=useState(""),[error,setError]=useState("");
 async function load(){const r=await fetch("/api/produtos");const d=await r.json();if(r.ok)setProducts(d.products||[]);else setError(d.error||"Erro ao carregar.")}
 useEffect(()=>{load()},[]);
 const filtered=useMemo(()=>products.filter(p=>(p.name+" "+p.sku).toLowerCase().includes(q.toLowerCase())),[products,q]);
 async function adjust(){if(!selected||Number(qty)<=0)return;setError("");setMsg("");const r=await fetch("/api/movimentacoes",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({product_id:selected.id,type,quantity:Number(qty),reason:reason||"Ajuste de inventário"})});const d=await r.json();if(!r.ok){setError(d.error||"Não foi possível ajustar.");return}setMsg("Inventário atualizado.");setSelected(null);setQty("");setReason("");load();}
 return <div className="shell"><Sidebar/><main className="main"><div className="topbar"><div><div className="eyebrow">CONTAGEM OPERACIONAL</div><h1 className="title">Inventário</h1><p className="muted">Confira o saldo físico e registre ajustes com rastreabilidade.</p></div><Link className="btn secondary" href="/historico">Ver histórico</Link></div>
 <section className="section card"><div style={{display:"flex",gap:10,flexWrap:"wrap"}}><input className="input" style={{margin:0,maxWidth:420}} placeholder="Buscar produto ou SKU..." value={q} onChange={e=>setQ(e.target.value)}/><span className="muted" style={{padding:"10px 4px"}}>{filtered.length} item(ns)</span></div></section>
 {msg&&<div className="section card" style={{borderColor:"rgba(52,211,153,.25)"}}>✓ {msg}</div>}{error&&<div className="section card" style={{borderColor:"rgba(251,113,133,.25)"}}>⚠ {error}</div>}
 <section className="section card"><div className="table-wrap"><table className="table"><thead><tr><th>Produto</th><th>SKU</th><th>Local</th><th>Saldo</th><th>Mínimo</th><th>Ação</th></tr></thead><tbody>{filtered.map(p=><tr key={p.id}><td><b>{p.name}</b></td><td>{p.sku}</td><td>{p.location||"—"}</td><td><strong>{p.stock_quantity}</strong> {p.unit||"UN"}</td><td>{p.minimum_stock}</td><td><button className="btn secondary" onClick={()=>setSelected(p)}>Ajustar</button></td></tr>)}</tbody></table></div></section>
 {selected&&<div className="card section"><div className="panel-head"><div><div className="eyebrow">AJUSTE</div><h2>{selected.name}</h2><span className="muted">Saldo atual: {selected.stock_quantity} {selected.unit||"UN"}</span></div><button className="btn secondary" onClick={()=>setSelected(null)}>Fechar</button></div><div className="form-grid"><label>Tipo<select className="input" value={type} onChange={e=>setType(e.target.value)}><option value="adjustment_in">Entrada de ajuste</option><option value="adjustment_out">Saída de ajuste</option><option value="loss">Perda</option><option value="damage">Avaria</option></select></label><label>Quantidade<input className="input" type="number" min="0.001" step="0.001" value={qty} onChange={e=>setQty(e.target.value)}/></label></div><label>Motivo<input className="input" value={reason} onChange={e=>setReason(e.target.value)} placeholder="Ex.: contagem física"/></label><button className="btn" onClick={adjust}>Registrar ajuste</button></div>}
 </main></div>;
}